import mongoose from 'mongoose';

// transaction model is used to store the information of a transaction that has occurred between two accounts. it is used to link the ledger entries of the from and to accounts. it also stores the status of the transaction and the ammount of the transaction. it is a reference for the user to know their transaction history and status.

// we using indexes on fromAccount and toAccount fields for fast searching of transactions by account id. this is important for generating account statements and for auditing purposes. it also helps in improving the performance of the system when there are a large number of transactions.

const transactionSchema = new mongoose.Schema({
    fromAccount: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'account',
        required: [true, 'Transaction must have a from account'],
        index: true,
    },
    toAccount: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'account',
        required: [true, 'Transaction must have a to account'],
        index: true,
    },
    status: {
        type: String,
        enum: {
            values: ['pending', 'completed', 'failed' , 'reversed'],
            message: 'Status must be either pending, completed or failed',
        },
        default: 'pending',
    },
    ammount :{
        type : Number,
        required : [true , 'Transaction must have a ammount'],
        min : [0 , "transiction ammount cannot be negativve"]
    },
    
    // idmpotency key to ensure that the same transaction is not processed multiple times in case of network issues or client retries.it is a unique identifier generated by the client side for each transaction request.
    
    idempotencyKey: {
        type: String,
        required: [true, 'Transaction must have an idempotency key'],
        unique: true,
        index: true,
    }
},{
    timestamps: true,
});

const transactionModel = mongoose.model('transaction', transactionSchema);
export default transactionModel;